# This is a basic workflow to help you get started with Actions

name: Run tests before PR to master

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events for the "master" branch
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-94777647f6ea5d34572a1b15c9b57e35b8c77b41
               
      - name: Run tests latest
        run: forge test -vv 
